INHERIT: mkdocs_base.yml

site_name: 'MkDocs Tau Delta'
site_url: https://TheodoreAD.github.io/mkdocs-taudelta
site_author: Teodor Dumitrescu <teodor.dumitrescu@gmail.com>
repo_url: https://github.com/TheodoreAD/mkdocs-taudelta
repo_name: TheodoreAD/mkdocs-taudelta
# TODO: make the edit icon smaller, the rest of the content is now smaller
edit_uri: edit/master/docs
docs_dir: docs
site_dir: html
# gh-deploy command settings
remote_branch: gh-pages
remote_name: origin

# If nothing is specified, navigation will be implicitly created using
# capitalized directory names and the H1 of each file, sorted alphanumerically
# used to be done using 'pages', now deprecated, new syntax is 'nav'
#nav:
# If using the regular nav section, please create a separate file
nav:
  - Home: index.md
  - live-editor.md
  - basic-markdown.md
  - enhanced-markdown.md
  - enhanced-markdown-code.md
  - admonition-blocks.md
  - mermaid.md
  - markmap.md
  - keys.md
  - emoji.md
  - unicode.md
  - material-icons.md
  - font-awesome.md
  - charts.md
  - favicon-and-logo.md
  - embedded_video.md
  - markdown-resources.md

# TODO: replace Nav section by awesome pages plugin .pages files in each dir
# https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
